MAS/MAS-war/src/java/managedbean/common/RoleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean.common;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import managedbean.application.MsgController;
import managedbean.application.NavigationController;
import mas.common.entity.Permission;
import mas.common.entity.SystemRole;
import mas.common.session.RoleSessionLocal;
import mas.common.session.SystemUserSessionLocal;
import mas.common.util.exception.NoSuchRoleException;
import mas.common.util.exception.ExistSuchRoleException;
import mas.common.util.exception.NoSuchPermissionException;
import mas.common.util.helper.RolePermission;
import mas.common.util.helper.UserMsg;

/**
 *
 * @author winga_000
 */
@Named(value = "roleController")
@RequestScoped
public class RoleController implements Serializable {

    @Inject
    UserController userController;
    @Inject
    NavigationController navigationController;
    @Inject
    MsgController msgController;

    @EJB
    private SystemUserSessionLocal systemUserSession;
    @EJB
    private RoleSessionLocal roleSession;

    private List<SystemRole> roleList;
    private List<SystemRole> roles;
    private List<String> roleNameList;
//    private List<Permission> rolePermissions;
    private List<Permission> permissionList;
    private List<RolePermission> rolePermissionList;
    private SystemRole selectedRole;

    /**
     * Creates a new instance of roleController
     */
    public RoleController() {
    }

    @PostConstruct
    public void init() {
        setRoleNameList();
        roles = getAllRoles();
    }

    public String createSystemRole(String roleName, String[] permissions) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().getFlash().setKeepMessages(true);
        try {
            roleSession.createSystemRole(roleName, permissions);
            context.addMessage(null, new FacesMessage("Successful", "Create new role: " + roleName + " successfully!"));
        } catch (ExistSuchRoleException ex) {
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", UserMsg.EXIST_ROLE_ERROR));
        } catch (NoSuchPermissionException ex) {
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", UserMsg.NO_PERMISSION_ERROR));
        }
        return navigationController.redirectToCreateRole();
    }

    public List<SystemRole> getAllRoles() {
        return roleSession.getAllRoles();
    }

    private void setRoleNameList() {
        List<SystemRole> roles = getAllRoles();
        roleNameList = new ArrayList<>();
        for (SystemRole role : roles) {
            roleNameList.add(role.getRoleName());
        }
    }

    public void onRoleSelected() throws NoSuchRoleException {
        permissionList = roleSession.getRolePermissions(selectedRole.getRoleName());
    }
    
    public String grantRolePermissions() {
        roleSession.grantRolePermissions(selectedRole, permissionList);
        msgController.addMessage("Grant role: " + selectedRole.getRoleName() + " with permissions");
        return navigationController.redirectToGrantRolePermissions();
    }
    
    public List<Permission> getRolePermissionsByRoleName(String roleName){
        try {
            return roleSession.getRolePermissions(roleName);
        } catch (NoSuchRoleException ex) {
            return null;
        }
    }
    
    public String deleteRole(String roleName){
        try {
            String role = roleSession.deleteRole(roleName);
            msgController.addMessage("Delete " + role + " successfully!");
        } catch (NoSuchRoleException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToViewAllRoles();
    }
    
    //Getter and Setter
    public UserController getUserController() {
        return userController;
    }

    public void setUserController(UserController userController) {
        this.userController = userController;
    }

    public List<String> getRoleNameList() {
        return roleNameList;
    }

    public void setRoleNameList(List<String> roleNameList) {
        this.roleNameList = roleNameList;
    }

    public List<SystemRole> getRoles() {
        return roles;
    }

    public void setRoles(List<SystemRole> roles) {
        this.roles = roles;
    }

    public List<SystemRole> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<SystemRole> roleList) {
        this.roleList = roleList;
    }

    public List<RolePermission> getRolePermissionList() {
        return rolePermissionList;
    }

    public void setRolePermissionList(List<RolePermission> rolePermissionList) {
        this.rolePermissionList = rolePermissionList;
    }

    public SystemRole getSelectedRole() {
        return selectedRole;
    }

    public void setSelectedRole(SystemRole selectedRole) {
        this.selectedRole = selectedRole;
    }

    public List<Permission> getPermissionList() {
        return permissionList;
    }
    
    public void setPermissionList(List<Permission> permissionList) {
        this.permissionList = permissionList;
    }

}

MAS/MAS-war/src/java/managedbean/common/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean.common;

import managedbean.application.NavigationController;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import mas.common.entity.SystemUser;
import mas.common.session.SystemUserSessionLocal;
import mas.common.util.exception.NoSuchEmailException;
import mas.common.util.exception.NoSuchUsernameException;
import mas.common.util.exception.ExistSuchUserException;
import mas.common.util.helper.CreateToken;
import util.helper.CountdownHelper;
import util.security.CryptographicHelper;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import managedbean.application.MsgController;
import mas.common.entity.Permission;
import mas.common.entity.SystemRole;
import mas.common.session.RoleSessionLocal;
import mas.common.util.exception.ExistSuchUserEmailException;
import mas.common.util.exception.NeedResetDigestException;
import mas.common.util.exception.NoSuchResetDigestException;
import mas.common.util.exception.NoSuchRoleException;
import mas.common.util.exception.UserInUseException;
import mas.common.util.helper.PermissionHelper;
import mas.common.util.helper.RolePermission;
import mas.common.util.helper.UserRolePermission;

/**
 *
 * @author winga_000
 */
@Named(value = "userController")
@RequestScoped
public class UserController implements Serializable {

    private final String TIMER_NAME_RESET_PASSWORD = "RESET_PASSWORD_TIMER";

    @Inject
    private NavigationController navigationController;
    @Inject
    private EmailController emailController;
    @Inject
    private MsgController msgController;

    @EJB
    private SystemUserSessionLocal systemUserSession;
    @EJB
    private RoleSessionLocal roleSession;
    private String username;
    private String password;
    private String email;
    private String resetDigest;
    private String newUsername;
    private String newPassword;
    private List<SystemUser> userList;
    private SystemUser selectedUser;
    private List<SystemRole> roleList;
    private List<UserRolePermission> userRolePermissionList;
    private List<RolePermission> rolePermissionList;
    private List<String> otherUsernames;
    private String name;
    private String address;
    private String department;
    private String phone;
    private List<SystemUser> filteredUsers;

   

    public UserController() {
    }

    @PostConstruct
    public void init() {
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        Map<String, Object> sessionMap = externalContext.getSessionMap();
        this.username = (String) sessionMap.get("username");
        initializeUser();
    }

    public String resetPasswordSendEmail(String email) throws InterruptedException {
        CountdownHelper countdownHelper = new CountdownHelper(systemUserSession);
        try {
            systemUserSession.verifySystemUserEmail(email);
            String resetDigest = createNewToken();
            String subject = "Reset Password";
            String mailContent = navigationController.toUnsecuredUsersFolder()
                    + "resetPassword.xhtml?faces-redirect=true&resetDigest=" + resetDigest + "&email=" + email;
            String receiver = email;
            emailController.sendEmail(subject, mailContent, receiver);
            systemUserSession.setResetDigest(email, resetDigest);

            countdownHelper.expireResetPasswoordCountDown(60 * 1000, email);//Auto expire password after 30mins

            msgController.addMessage("Please check your email to reset password");
            return navigationController.redirectToHome() + "?faces-redirect=true";
        } catch (NoSuchEmailException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return navigationController.toPasswordResetSendEmail();
        }
    }

    public String resetPassword() {
//        if (!newPassword.equals(newConfirmPassword)) {
//            msgController.addErrorMessage("The two passwords entered are different.");
//            return "";
//        }
        CryptographicHelper cryptographicHelper = new CryptographicHelper();
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        externalContext.getFlash().setKeepMessages(true);
        Map<String, String> params = externalContext.getRequestParameterMap();
        String userEmail = params.get("email");
        String resetDigest = params.get("resetDigest");
        try {
            systemUserSession.resetPassword(userEmail, resetDigest, cryptographicHelper.doMD5Hashing(newPassword));
            msgController.addMessage("Password reset successfully, you can login with new password now");
            return navigationController.redirectToLogin();
        } catch (NoSuchEmailException | NeedResetDigestException | NoSuchResetDigestException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return navigationController.redirectToPasswordResetSendEmail();
        }
    }

    public String changePassword(String oldPassword) {
        try {
            CryptographicHelper cryptographicHelper = new CryptographicHelper();
            if (!cryptographicHelper.doMD5Hashing(oldPassword).equals(password)) {
                msgController.addErrorMessage("Old password entered is incorrect.");
                return "";
            }
            newPassword = cryptographicHelper.doMD5Hashing(newPassword);
            systemUserSession.changePassword(username, newPassword);
            msgController.addMessage("Change password successfully!");
            return navigationController.redirectToWorkspace();
        } catch (NoSuchUsernameException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.toChangePassword();
    }

    public String createNewToken() {
        return CreateToken.createNewToken();
    }

    public String createUser(String username, String name, String email,
            String phone, String address, String department) {
        try {
            String newPassword = createNewToken();
            systemUserSession.createUser(username, newPassword, name, email, phone, address, department, roleList);
            String resetDigest = createNewToken();
            String subject = "Reset Password";
            String mailContent = "Please reset password first using the following link: \n" + navigationController.toUnsecuredUsersFolder() + "resetPassword.xhtml?faces-redirect=true&resetDigest=" + resetDigest + "&email=" + email;
            String receiver = email;
            emailController.sendEmail(subject, mailContent, receiver);
            systemUserSession.setResetDigest(email, resetDigest);
            msgController.addMessage("New user " + username + " is created successfuly!");
            cleanAttributeValue();
            return navigationController.redirectToCreateUser();
        } catch (ExistSuchUserException | NoSuchEmailException | NoSuchRoleException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return navigationController.toCreateUser();
        }
    }

    public List<SystemUser> getAllUsers() {
        return systemUserSession.getAllUsers();
    }

    public List<String> getAllOtherUsernames() {
        otherUsernames = systemUserSession.getAllOtherUsernames(username);
        return otherUsernames;
    }

    public String assignUserRoles() {
        systemUserSession.assignUserToRole(selectedUser, roleList);
        msgController.addMessage("Assign user:" + selectedUser.getUsername() + " with roles successuflly");
        cleanAttributeValue();
        return navigationController.redirectToAssignUserRoles();
    }

    public List<SystemRole> getUserRoles() throws NoSuchUsernameException {
        return systemUserSession.getUserRoles(username);
    }

    public List<SystemRole> getUserRolesByUsername(String username) throws NoSuchUsernameException {
        return systemUserSession.getUserRoles(username);
    }

    public void onUserSelected() throws NoSuchUsernameException {
//        rolePermissionList = systemUserSession.getUserRolesPermissions(selectedUser.getUsername());
        roleList = systemUserSession.getUserRoles(selectedUser.getUsername());
    }

    public boolean hasRole(String roleName) {
        return systemUserSession.hasRole(username, roleName);
    }

    public boolean isAdmin() {
        return systemUserSession.isAdmin(username);
    }

    public SystemUser getUserByEmail(String email) throws NoSuchEmailException {
        return systemUserSession.getSystemUserByEmail(email);
    }

     public SystemUser getUserByUsername() throws NoSuchUsernameException {
        return systemUserSession.getSystemUserByName(username);
    }

    public void cleanAttributeValue() {
        selectedUser = null;
        roleList = null;
        userRolePermissionList = null;
        rolePermissionList = null;
    }

    public String updateUserProfile() {
        try {
            systemUserSession.updateUserProfile(username, name, email, phone, address, department);
            msgController.addMessage("Update user profile successfully!");
        } catch (NoSuchUsernameException | ExistSuchUserEmailException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return navigationController.toEditUserProfile();
        }
        return navigationController.redirectToViewUserProfile();
    }

    public List<Permission> getUserPermissions() {
        return systemUserSession.getUserPermissions(username);
    }

MAS/MAS-war/web/views/internal/secured/common/users/adminWorkspace.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/WorkspaceTemplate.xhtml"
                xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="title">
        Merlion Airline System Admin Workplace
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h2>Welcome</h2>
            <br/>
            <h:outputText value="This is a place you start to work"></h:outputText>
        </h:form>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/common/users/assignUserRoles.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/WorkspaceTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Assign User Roles
    </ui:define>

    <ui:define name="content">
        <p:panel header="Assign Roles To Users">
            <h:form id="assignUserRoles">
                <p:panelGrid class="access-control" columns="2">
                    <p:panel header="Select user">
                        <p:selectOneListbox id="assignUserRoles-userList" value="#{userController.selectedUser}"  converter="userConverter" 
                                         var="user" filter="true" filterMatchMode="contains" style="width:300px;">

                            <p:ajax update="assignUserRolesPanel,selectRoles" listener="#{userController.onUserSelected()}"/>
                            <f:selectItems value="#{userController.allUsers}" var="user" itemLabel="#{user.username}" itemValue="#{user}" />
                            <p:column>
                                <p:outputLabel value="#{user.username}" />
                            </p:column>

                        </p:selectOneListbox>
                    </p:panel>

                    <p:panel header="Select user roles" id="selectRoles">
                        <p:outputLabel value="Select user roles:" />

                        <p:selectManyMenu id="assignUserRoles-roleList" value="#{userController.roleList}" converter="roleConverter"
                                          var="role" filter="true" filterMatchMode="contains" showCheckbox="true" style="width:100%; min-width: 400px">
                            <f:selectItems value="#{roleController.allRoles}" var="role" itemLabel="#{role.roleName}" itemValue="#{role}"/>

                            <p:column>
                                <h:outputText value="#{role.roleName}"  />
                            </p:column>
                        </p:selectManyMenu>
                    </p:panel>
                </p:panelGrid>
                
                <p:dataTable id="assignUserRolesPanel" value="#{userController.roleList}" var="role" emptyMessage="No role selected" class="userRoleDataTable" tableStyleClass="table-small-font">
                    <f:facet name="header">
                        Existing user roles
                    </f:facet>
                    <p:column headerText="Roles">
                        <h:outputText value="#{role.roleName}" />
                    </p:column>

                    <p:column headerText="Permisssions">
                        <p:dataTable value="#{roleController.getRolePermissionsByRoleName(role.roleName)}" var="permission">
                            <p:column>
                                <p:outputLabel value="#{permission.permissionName}"/>
                            </p:column>
                        </p:dataTable>
                    </p:column>
                </p:dataTable>
                <p:commandButton action="#{userController.assignUserRoles()}" value="Assign" update="messages"/>    

            </h:form>        
        </p:panel>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/common/users/changePassword.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/WorkspaceTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Change Password
    </ui:define>

    <ui:define name="content">
        <h:form>
            <p:panel header="Change Password">
                <p:panelGrid columns="2">
                    <p:outputLabel value="Old password: " />
                    <p:password id="oldPassword" required="true" binding="#{oldPassword}" requiredMessage="Please enter confirm password" />
                    
                    <p:outputLabel value="New password: "/>
                    <p:password id="password" value="#{userController.newPassword}" required="true" requiredMessage="Please enter password">
                        <f:validator validatorId="passwordValidator" />
                        <f:attribute name="confirmPassword" value="#{confirmPassword}" />
                    </p:password>

                    <p:outputLabel value="Confirm new password: " />
                    <p:password id="confirmPassword" required="true" binding="#{confirmPassword}" requiredMessage="Please enter confirm password" />
                </p:panelGrid>
                <p:commandButton value="save" action="#{userController.changePassword(oldPassword.value)}" update="messages" />
            </p:panel>
        </h:form>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/common/users/createUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/WorkspaceTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:b="botDetectFacelets">

    <ui:define name="title">
        Create new user
    </ui:define>

    <ui:define name="content">
        <h:form id="createUserForm">
            <p:panel header="Creat User">
                <p:panelGrid columns="2">
                    <p:panel header="Basic information">
                        <p:panelGrid columns="2">
                            <p:outputLabel for="username" value="Username"/>
                            <p:inputText class="userProfileInput" required="true" requiredMessage="Please enter username" id="username" binding="#{newUsername}"/>
                            
                            <p:outputLabel for="name" value="Name"/>
                            <p:inputText class="userProfileInput" required="true" requiredMessage="Please enter name" id="name" binding="#{newName}"/>           
                            
                            <p:outputLabel for="email" value="Email"/>
                            <p:inputText class="userProfileInput" required="true" requiredMessage="Please enter email" validatorMessage="Invalid email format" id="email" binding="#{newEmail}">
                                <p:ajax update="messages" event="blur" />
                                <f:validateRegex
                                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                            </p:inputText>
                            
                            <h:outputText value="Phone"/>
                            <p:inputMask id="phone" mask="99999999" class="userProfileInput"  binding="#{newPhone}" >
                                <p:tooltip id="phone_tooltip" for="phone" showEvent="focus" hideEvent="blur" 
                                           value="Phone number must be 8-digit number"/>
                            </p:inputMask>                           
                            
                            <h:outputText value="Address"/>
                            <p:inputText class="userProfileInput" binding="#{newAddress}"/>
                            
                            <p:outputLabel for="department" value="Department"/>
                            <p:inputText class="userProfileInput" id="department" required="true" requiredMessage="Please enter department" binding="#{newDepartment}"/>
                        </p:panelGrid>
                    </p:panel>
                    <p:panel header="Select Roles">
                        <p:selectManyMenu id="advanced" value="#{userController.roleList}" converter="roleConverter"
                                          var="role" filter="true" filterMatchMode="contains" showCheckbox="true" style="width:100%; min-width: 400px">
                            <f:selectItems value="#{roleController.roles}" var="role" itemLabel="#{role.roleName}" itemValue="#{role}"/>
                            <p:ajax update="permissionTable"/>
                            <p:column>
                                <p:outputLabel value="#{role.roleName}"  />
                            </p:column>
                        </p:selectManyMenu>
                    </p:panel>

                </p:panelGrid>
                <p:dataTable id="permissionTable" value="#{userController.roleList}" var="role" emptyMessage="No role selected" class="userRoleDataTable" tableStyleClass="table-small-font">
                    <f:facet name="header">
                        Role Permissions
                    </f:facet>
                    <p:column headerText="Roles">
                        <h:outputText value="#{role.roleName}" />
                    </p:column>

                    <p:column headerText="Permisssions">
                        <p:dataTable value="#{roleController.getRolePermissionsByRoleName(role.roleName)}" var="permission">
                            <p:column>
                                <p:outputLabel value="#{permission.permissionName}"/>
                            </p:column>
                        </p:dataTable>
                    </p:column>
                </p:dataTable>                

                <p:commandButton action="#{userController.createUser(newUsername.value, newName.value, 
                                           newEmail.value, newPhone.value, newAddress.value, newDepartment.value)}" value="Create" update="messages"/>    

            </p:panel>
        </h:form>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/common/users/viewAllUsers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/WorkspaceTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        View all users
    </ui:define>

    <ui:define name="content">
        <h:form>
            <p:panel header="View Users">
                <p:dataTable value="#{userController.allUsers}" var="user" tableStyleClass="table-small-font"
                             paginator="true" paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="5,10,15" rowKey="#{aircraft.aircraftId}" rows="3">
                    <p:column headerText="Username">
                        <p:outputLabel value="#{user.username}"/>
                    </p:column>

                    <p:column headerText="Email">
                        <p:outputLabel value="#{user.email}" />
                    </p:column>

                    <p:column headerText="Role">
                        <p:dataTable value="#{userController.getUserRolesByUsername(user.username)}" var="role" tableStyleClass="table-small">
                            <p:column>
                                <p:outputLabel value="#{role.roleName}" />
                            </p:column>
                        </p:dataTable>
                    </p:column>


                    <p:column headerText="Permissions">
                        <p:dataTable value="#{userController.getUserPermissions(user.username)}" var="permission" tableStyleClass="table-small">
                            <p:column>
                                <p:outputLabel value="#{permission.permissionName}" />
                            </p:column>
                        </p:dataTable>
                    </p:column>

                    <p:column style="width:32px;text-align: center">
                        <p:commandButton class="actionButton" action="#{userController.deleteUser(user.username)}" icon="ui-icon-close" update="messages">
                            <p:confirm header="Confirmation" message="Are you sure to delete the user?" icon="ui-icon-alert" />
                        </p:commandButton>
                    </p:column>
                    <p:column style="width:32px;text-align: center"  rendered="#{!user.getLocked()}">
                        <p:commandButton class="actionButton" action="#{userController.lockUser(user.username)}" icon="ui-icon-locked" update="messages" >
                            <p:confirm header="Confirmation" message="Are you sure to lock the user?" icon="ui-icon-alert" />
                        </p:commandButton>
                    </p:column>
                    <p:column style="width:32px;text-align: center"  rendered="#{user.getLocked()}">
                        <p:commandButton class="actionButton" action="#{userController.unlockUser(user.username)}" icon="ui-icon-unlocked" update="messages">
                            <p:confirm header="Confirmation" message="Are you sure to unlock the user?" icon="ui-icon-alert" />
                        </p:commandButton>
                    </p:column>
                </p:dataTable>
                <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                    <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                </p:confirmDialog>
            </p:panel>
        </h:form>
    </ui:define>

</ui:composition>