MAS/MAS-war/src/java/managedbean/ais/BookingClassController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean.ais;

import ams.ais.entity.BookingClass;
import ams.ais.entity.TicketFamily;
import ams.ais.util.exception.ExistSuchBookingClassNameException;
import ams.ais.util.exception.NoSuchBookingClassException;
import ams.ais.util.helper.FlightSchCabinClsTicFamBookingClsHelper;
import ams.ais.session.RevMgmtSessionLocal;
import ams.ais.session.SeatReallocationSessionLocal;
import ams.ais.session.ProductDesignSessionLocal;
import ams.ais.util.exception.DuplicatePriceException;
import ams.ais.util.exception.NeedBookingClassException;
import ams.ais.util.exception.WrongSumOfBookingClassSeatQtyException;
import ams.ais.util.exception.WrongSumOfTicketFamilySeatQtyException;
import ams.ais.util.helper.BookingClassHelper;
import ams.ais.util.helper.TicketFamilyBookingClassHelper;
import ams.aps.util.exception.NoSuchAircraftCabinClassException;
import ams.aps.util.exception.NoSuchAircraftException;
import ams.aps.util.exception.NoSuchFlightSchedulException;
import ams.aps.util.exception.NoSuchFlightScheduleBookingClassException;
import ams.crm.util.helper.ChannelHelper;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.component.UIComponent;
import javax.inject.Named;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import managedbean.application.MsgController;
import managedbean.application.NavigationController;

@Named(value = "bookingClassController")
@ViewScoped
public class BookingClassController implements Serializable {

    @Inject
    private MsgController msgController;
    @Inject
    private NavigationController navigationController;

    @EJB
    private RevMgmtSessionLocal revMgmtSession;
    @EJB
    private SeatReallocationSessionLocal seatReallocationSession;
    @EJB
    private ProductDesignSessionLocal productDesignSession;

    private String bookingClassName;
    private Long flightScheduleId;
    private List<FlightSchCabinClsTicFamBookingClsHelper> flightSchCabinClsTicFamBookingClsHelpers;
    private float basicPrice;
    private BookingClass selectedBookingClass;
    private TicketFamily selectedTicketFamily;
    private Map<Long, Float> priceMap = new HashMap<>();
    private Map<Long, Float> priceCoefficientMap = new HashMap<>();
    private String useless = null;

    /**
     * Creates a new instance of BookingClassController
     */
    @PostConstruct
    public void Init() {
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        Map<String, Object> sessionMap = externalContext.getSessionMap();
        this.flightScheduleId = (Long) sessionMap.get("flightScheduleId");
        System.out.println("Initialize Booking Class Controler: ");
        System.out.println("FlightScheduleId: " + flightScheduleId);
        initialHelper();
        initialPrice();
        System.out.println("Helper: " + flightSchCabinClsTicFamBookingClsHelpers);
    }

    public BookingClassController() {
    }

    public List<TicketFamily> getAllTicketFamily() {
        return productDesignSession.getAllTicketFamily();

    }

    public List<BookingClass> getAllBookingClasses() {
        return revMgmtSession.getAllBookingClasses();
    }

    public String createBookingClass() {
        try {
            revMgmtSession.createBookingClass(bookingClassName, selectedTicketFamily, ChannelHelper.ARS);
            msgController.addMessage("Create booking class successfully!");
        } catch (ExistSuchBookingClassNameException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }

        return navigationController.redirectToCreateBookingClass();
    }

    public String deleteBookingClass() {
        try {
            System.out.printf("selected booking class is: " + selectedBookingClass);
            revMgmtSession.deleteBookingClass(selectedBookingClass.getName());
            msgController.addMessage("Booking class is deleted successfully!");
        } catch (NoSuchBookingClassException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToDeleteBookingClass();
    }

    public String assignFlightScheduleBookingClass() {
        try {
            revMgmtSession.assignFlightScheduleBookingClass(flightScheduleId, flightSchCabinClsTicFamBookingClsHelpers);
            msgController.addMessage("assign flight schedule booking class succesffully!");

            return navigationController.redirectToViewFlightSchedule();
        } catch (NoSuchFlightSchedulException | NoSuchFlightScheduleBookingClassException | NeedBookingClassException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return "";
        }
    }

    public String allocateSeats() {
        try {
            revMgmtSession.allocateSeats(flightScheduleId, flightSchCabinClsTicFamBookingClsHelpers);
            msgController.addMessage("Allocate seats succesfully!");
        } catch (NoSuchAircraftCabinClassException | NoSuchAircraftException | NoSuchFlightScheduleBookingClassException | WrongSumOfBookingClassSeatQtyException | WrongSumOfTicketFamilySeatQtyException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return "";
        }
        return navigationController.redirectToViewFlightSchedule();
    }

    public String priceBookingClasses() {
        try {
            revMgmtSession.priceBookingClasses(flightScheduleId, flightSchCabinClsTicFamBookingClsHelpers, priceMap);
            List<Date> checkPoints = new ArrayList<>();

            checkPoints = seatReallocationSession.yieldManagement(flightScheduleId);
            sendYieldMgtReminder(checkPoints);

            msgController.addMessage("Price booking class succesfully!");
        } catch (NoSuchFlightScheduleBookingClassException | DuplicatePriceException ex) {
            msgController.addErrorMessage(ex.getMessage());
            return "";
        }

        return navigationController.redirectToViewFlightSchedule();
    }

    private void sendYieldMgtReminder(List<Date> checkDates) {
        Timer[] timers = new Timer[checkDates.size()];
        int count = 0;
        for (Date date : checkDates) {
            timers[count] = new Timer();
            timers[count].schedule(new YieldMgtTask(), date);
            count++;

        }

    }

    class YieldMgtTask extends TimerTask {

        @Override
        public void run() {
            msgController.sendReminder("It's time to perform yield management for flight schedule " + flightScheduleId);
        }

    }

    public void onPriceCoefficientChange(AjaxBehaviorEvent event) {
        String id = (String) ((UIComponent) event.getComponent()).getId();
        float priceCoefficient = (float) ((UIComponent) event.getComponent()).getAttributes().get("value");
        Long bookingClassId = Long.parseLong(id.split("priceCoefficient")[1]);
        priceMap.put(bookingClassId, getCalculatedPrice(priceCoefficient));
    }

    public void initialPrice() {
        if (!flightSchCabinClsTicFamBookingClsHelpers.isEmpty()) {
            for (FlightSchCabinClsTicFamBookingClsHelper helper : flightSchCabinClsTicFamBookingClsHelpers) {
                for (TicketFamilyBookingClassHelper tfbcHelper : helper.getTicketFamilyBookingClassHelpers()) {
                    for (BookingClassHelper bcHelper : tfbcHelper.getBookingClassHelpers()) {
                        if (bcHelper != null) {
                            priceMap.put(bcHelper.getBookingClass().getBookingClassId(), bcHelper.getPrice());
                            priceCoefficientMap.put(bcHelper.getBookingClass().getBookingClassId(), bcHelper.getPriceCoefficient());
                            basicPrice = bcHelper.getBasicPrice();
                        }
                    }
                }
            }
        }
    }

    private void initialHelper() {
        flightSchCabinClsTicFamBookingClsHelpers = revMgmtSession.getFlightSchCabinClsTicFamBookingClsHelpers(flightScheduleId);
    }

    public float getCalculatedPrice(float priceCoefficient) {
        return priceCoefficient * basicPrice;
    }

    //Getter and Setter
    public String getBookingClassName() {
        return bookingClassName;
    }

    public void setBookingClassName(String bookingClassName) {
        this.bookingClassName = bookingClassName;
    }

    public List<FlightSchCabinClsTicFamBookingClsHelper> getFlightSchCabinClsTicFamBookingClsHelpers() {
        return flightSchCabinClsTicFamBookingClsHelpers;
    }

    public void setFlightSchCabinClsTicFamBookingClsHelpers(List<FlightSchCabinClsTicFamBookingClsHelper> flightSchCabinClsTicFamBookingClsHelpers) {
        this.flightSchCabinClsTicFamBookingClsHelpers = flightSchCabinClsTicFamBookingClsHelpers;
    }

    public Long getFlightScheduleId() {
        return flightScheduleId;
    }

    public void setFlightScheduleId(Long flightScheduleId) {
        this.flightScheduleId = flightScheduleId;
    }

    public float getBasicPrice() {
        return basicPrice;
    }

    public void setBasicPrice(float basicPrice) {
        this.basicPrice = basicPrice;
    }

    public BookingClass getSelectedBookingClass() {
        return selectedBookingClass;
    }

    public void setSelectedBookingClass(BookingClass selectedBookingClass) {
        this.selectedBookingClass = selectedBookingClass;
    }

    public TicketFamily getSelectedTicketFamily() {
        return selectedTicketFamily;
    }

MAS/MAS-war/src/java/managedbean/ais/CabinClassController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean.ais;

import ams.ais.entity.CabinClass;
import ams.ais.entity.TicketFamily;
import ams.ais.session.ProductDesignSessionLocal;
import ams.ais.util.exception.ExistSuchCabinClassNameException;
import ams.ais.util.exception.ExistSuchCabinClassTypeException;
import ams.ais.util.exception.NoSuchCabinClassException;
import ams.ais.util.exception.NoSuchTicketFamilyException;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import managedbean.application.MsgController;
import managedbean.application.NavigationController;

/**
 *
 * @author Bowen
 */
@Named(value = "cabinClassController")
@RequestScoped
public class CabinClassController implements Serializable{

    @Inject
    private NavigationController navigationController;
    @Inject
    private MsgController msgController;
    
    @EJB
    private ProductDesignSessionLocal productDesignSession;
    
    private String oldname;

    public String getOldname() {
        return oldname;
    }

    public void setOldname(String oldname) {
        this.oldname = oldname;
    }
    private String type;
    private String name;
    private CabinClass selectedCabinClass;

    public CabinClassController() {
    }

    public String createCabinClass(){
        try {
            productDesignSession.createCabinClass(type, name);
            msgController.addMessage("Create cabin class successfully!");
        } catch (ExistSuchCabinClassNameException | ExistSuchCabinClassTypeException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToCreateCabinClass();
    }
    
    public List<CabinClass> getAllCabinClass() {
        return productDesignSession.getAllCabinClass();
    }
    
    public void deleteCabinClass() {
        try{
        productDesignSession.deleteCabinClass(selectedCabinClass.getName());
        msgController.addMessage("Delete cabin class successfully");
        } catch (NoSuchCabinClassException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
          
    }
    
    public String updateCabinClass() {
        try {
            System.out.println("selected cabin class name is: "+selectedCabinClass);
            productDesignSession.updateCabinClass(selectedCabinClass.getCabinClassId(),selectedCabinClass.getType(),selectedCabinClass.getName());
            msgController.addMessage("Edit cabin class successfully!");
        }catch( ExistSuchCabinClassNameException | NoSuchCabinClassException | ExistSuchCabinClassTypeException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToViewAllCabinClass();
        
    }
    
    public List<TicketFamily> getCabinClassTicketFamilys(String type){
        List<TicketFamily> ticketFamilys;
        try {
            ticketFamilys = productDesignSession.getCabinClassTicketFamilys(type);
        } catch (NoSuchTicketFamilyException e) {
            return null;
        }
        return ticketFamilys;          
    }
    
    public List<String> getCabinClassTicketFamilyNames(String type){
        return productDesignSession.getCabinClassTicketFamilyNames(type);
    }
    
    public CabinClass getCabinClassByName(String name){
        try {
            return productDesignSession.getCabinClassByName(name);
        } catch (NoSuchCabinClassException ex) {
            return null;
        }
    }
    
    //Getter and Setter
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CabinClass getSelectedCabinClass() {
        return selectedCabinClass;
    }

    public void setSelectedCabinClass(CabinClass selectedCabinClass) {
        this.selectedCabinClass = selectedCabinClass;
    }
    
}

MAS/MAS-war/src/java/managedbean/ais/RuleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managedbean.ais;

import ams.ais.entity.Rule;
import ams.ais.session.ProductDesignSessionLocal;
import ams.ais.util.exception.ExistSuchRuleException;
import ams.ais.util.exception.NoSuchRuleException;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import managedbean.application.MsgController;
import managedbean.application.NavigationController;

/**
 *
 * @author Bowen
 */
@Named(value = "ruleController")
@RequestScoped
public class RuleController implements Serializable{
    @Inject
    private NavigationController navigationController;
    @Inject
    private MsgController msgController;
    
    @EJB ProductDesignSessionLocal productDesignSession;
    
    private String oldname;
    private String name;
    private Rule selectedRule;
    private String description;

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Rule getSelectedRule() {
        return selectedRule;
    }

    public void setSelectedRule(Rule selectedRule) {
        this.selectedRule = selectedRule;
    }

    public String getOldname() {
        return oldname;
    }

    public void setOldname(String oldname) {
        this.oldname = oldname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    /**
     * Creates a new instance of RuleController
     */
    public RuleController() {
    }
    
    public String createRule (){
        try {
            productDesignSession.createRule(name,description);
            msgController.addMessage("Create New Rule successfully!");
        } catch (ExistSuchRuleException ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToCreateRule();
    }
    
    
    public List<Rule> getAllRule() {
        return productDesignSession.getAllRules();
    }
    
    public void deleteRule() {
        try{
        productDesignSession.deleteRule(selectedRule.getName());
        System.out.printf("name is :"+selectedRule.getName());
        msgController.addMessage("Delete rule successfully");
        } catch (NoSuchRuleException ex) {
        msgController.addErrorMessage(ex.getMessage());
        }    
    }
    
    public String updateRule() {
        try {
            productDesignSession.updateRule(selectedRule.getRuleId(),selectedRule.getName(),selectedRule.getDescription());
            msgController.addMessage("Edit rule successfully!");
        }catch( ExistSuchRuleException | NoSuchRuleException  ex) {
            msgController.addErrorMessage(ex.getMessage());
        }
        return navigationController.redirectToViewAllRules();
        
    }
}

MAS/MAS-war/web/views/internal/secured/ais/booking_class/assignFlightScheduleBookingClasses.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/AisTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="title">
        APS - Assign Flight Schedule Booking Classes
    </ui:define>

    <ui:define name="content">
        <h:form>
            <p:panel id="seatAllocation" header="Assign Flight Schedule Booking Classes" style="margin-bottom:20px">
                <p:panelGrid>
                    <f:facet name="header">
                        <p:row>
                            <p:column colspan="1">Cabin Class</p:column>
                            <p:column colspan="1">Ticket Family</p:column>
                            <p:column colspan="1">Booking Class</p:column>
                        </p:row>
                    </f:facet>
                    <c:forEach var="helper" items="#{bookingClassController.flightSchCabinClsTicFamBookingClsHelpers}">
                        <p:row>
                            <p:column colspan="1">#{helper.cabinClass.name}</p:column>
                            <p:column colspan="2">
                                <p:panelGrid columns="2" >
                                    <c:forEach var="tf" items="#{helper.ticketFamilyBookingClassHelpers}">
                                            <p:outputLabel value="#{tf.ticketFamily.name}" style="width: 80px;"/>
                                            <p:selectManyMenu value="#{tf.bookingClasses}" converter="bookingClassConverter"
                                                              var="bookingClass" showCheckbox="true" style="width:100px;">
                                                <f:selectItems value="#{flightScheduleController.getTicketFamilyBookingClasses(helper.cabinClass.name, tf.ticketFamily.name)}" 
                                                               var="bookingClass" itemLabel="#{bookingClass.name}" itemValue="#{bookingClass}" />
                                                <p:column>
                                                    <h:outputText value="#{bookingClass.name}"  />
                                                </p:column>
                                            </p:selectManyMenu>
                                    </c:forEach>
                                </p:panelGrid>
                            </p:column>
                        </p:row>
                    </c:forEach>

                </p:panelGrid>
                <p:commandButton value="Save" action="#{bookingClassController.assignFlightScheduleBookingClass()}" update="messages"/>

            </p:panel>            
        </h:form>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/ais/booking_class/createBookingClass.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/AisTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        Create Booking Class
    </ui:define>

    <ui:define name="content">
        <f:facet name="header">
            Add Booking Class
        </f:facet>
        <h:form id="createBookingClassForm">
            <p:panelGrid columns="2">
                <p:outputLabel value="Booking class name: "/>
                <p:inputText value="#{bookingClassController.bookingClassName}"/>
                <p:outputLabel for="type" value="Ticket Family:" />
                <p:selectOneMenu id="type" var="bc" value="#{bookingClassController.selectedTicketFamily}" converter="ticketFamilyConverter" style="width:300px" filter="true" filterMatchMode="startsWith">
                    <f:selectItem itemLabel="Select" itemValue="" noSelectionOption="true" />
                    <f:selectItems value="#{bookingClassController.allTicketFamily}" var="ticketFamily" itemLabel="#{ticketFamily.type}-#{ticketFamily.name}"/>
                    <p:column>
                        <h:outputText value="#{bc.type}"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{bc.cabinClass.name}"/>
                    </p:column>
                    <p:column>
                        <h:outputText value="#{bc.name}"/>
                    </p:column>
                </p:selectOneMenu>
            </p:panelGrid>

            <p:separator/>
            <p:commandButton action="#{bookingClassController.createBookingClass()}" value="Create" update="messages" />
        </h:form>
    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/ais/booking_class/seatAllocation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/AisTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <ui:define name="title">
        Seat Allocation
    </ui:define>

    <ui:define name="content">
        <h:form>
            <p:panel id="seatAllocation" header="Seat Allocation" style="margin-bottom:20px">
                <p:panelGrid>
                    <f:facet name="header">
                        <p:row>
                            <p:column colspan="2">Cabin Class</p:column>
                            <p:column colspan="2">Ticket Family</p:column>
                            <p:column colspan="2">Booking Class</p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="1">Name</p:column>
                            <p:column colspan="1">Seat Quantity</p:column>
                            <p:column colspan="1">Name</p:column>
                            <p:column colspan="1">Seat Quantity</p:column>
                            <p:column colspan="1">Name</p:column>
                            <p:column colspan="1">Seat Quantity</p:column>
                        </p:row>
                    </f:facet>
                    <c:forEach var="helper" items="#{bookingClassController.flightSchCabinClsTicFamBookingClsHelpers}">
                        <p:row>
                            <p:column colspan="1">#{helper.cabinClass.name}</p:column>
                            <p:column colspan="1">#{helper.seatQty} seats</p:column>
                            <p:column colspan="4">
                                <p:panelGrid columns="2">
                                    <c:forEach var="tf" items="#{helper.ticketFamilyBookingClassHelpers}">
                                        <p:panelGrid columns="2">
                                        <p:outputLabel value="#{tf.ticketFamily.name}" />
                                        <p:inputText value="#{tf.seatQty}" />
                                        </p:panelGrid>
                                            <p:column colspan="2">
                                                <c:forEach var="bc" items="#{tf.bookingClassHelpers}">
                                                    <p:panelGrid columns="2">
                                                        <p:outputLabel value="#{bc.bookingClass.name}" />
                                                        <p:inputText value="#{bc.seatQty}" />
                                                    </p:panelGrid>
                                                </c:forEach>
                                            </p:column>
                                    </c:forEach>
                                </p:panelGrid>
                            </p:column>
                        </p:row>
                    </c:forEach>

                </p:panelGrid>
                <p:commandButton value="Save" action="#{bookingClassController.allocateSeats()}" update="messages"/>

            </p:panel>
        </h:form>

    </ui:define>

</ui:composition>

MAS/MAS-war/web/views/internal/secured/ais/booking_class/viewBookingClass.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../../../../../template/AisTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    
      <ui:define name="title">
        View All Booking Class
    </ui:define>

    <ui:define name="content">
        <p:dataTable value="#{bookingClassController.allBookingClasses}" var="bookingClass" style="margin-bottom:40px" rows="10"
                     paginator="true" tableStyleClass="table-small-font"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                     rowsPerPageTemplate="10,15,30">
            
            <f:facet name="header">
                Booking Class
            </f:facet>
            <p:column headerText="Booking Class Name">
                <p:outputLabel value="#{bookingClass.name}"/>
            </p:column>
            
            <p:column headerText="Ticket Family Type">
                <p:outputLabel value="#{bookingClass.ticketFamily.type}"/>
            </p:column>
            
            <p:column headerText="Ticket Family Name">
                <p:outputLabel value="#{bookingClass.ticketFamily.name}"/>
            </p:column>
            
            <p:column headerText="Edit" style="width:32px;text-align: center">
                <h:form> <p:commandButton update="bookingClassDialog" oncomplete="PF('bookingClassDialog').show()" icon="ui-icon-pencil">
                        <f:setPropertyActionListener value="#{bookingClass}" target="#{productDesignEditController.selectedBookingClass}" />
                    </p:commandButton></h:form>
            </p:column>
            
            <p:column headerText="Delete" style="width:50px;text-align: center">
                <h:form> <p:commandButton update="bookingClassDeleteDialog" oncomplete="PF('bookingClassDeleteDialog').show()" icon="ui-icon-trash">
                        <f:setPropertyActionListener value="#{bookingClass}" target="#{productDesignDeleteController.selectedBookingClass}" />
                    </p:commandButton></h:form>
            </p:column>
            
        </p:dataTable>

        <p:dialog id="bookingClassDialog" header="Edit Booking Class:  #{productDesignEditController.selectedBookingClass.name}" widgetVar="bookingClassDialog" modal="true" appendTo="@(body)" showEffect="fade" hideEffect="fade" resizable="false">
            <h:form>
                <p:panel id="bookingClassDetail">
                    <p:panelGrid>
                        <p:row> 
                            <p:column>
                                <p:outputLabel value="Booking Class Name: " />
                            </p:column>
                            
                            <p:column>
                                <p:inputText value="#{productDesignEditController.selectedBookingClass.name}" >
                                </p:inputText>
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                </p:panel>
                <p:commandButton value="Submit" action="#{navigationController.redirectToViewAllBookingClass()}" actionListener="#{productDesignEditController.updateBookingClass()}" oncomplete="PF('bookingClassDialog').hide()"/>
            </h:form>
        </p:dialog>
        
        <p:dialog id="bookingClassDeleteDialog" header="Are you sure you want to delete the Booking Class:  #{productDesignDeleteController.selectedBookingClass.name}" widgetVar="bookingClassDeleteDialog" modal="true" appendTo="@(body)" showEffect="fade" hideEffect="fade" resizable="false">
            <h:form>
                <p:panel id="bookingClassDeleteDetail">
                    <p:panelGrid>
                        <p:row> 
                            <p:column>
                                <p:outputLabel value="Booking Class: " />
                            </p:column>
                            <p:column>
                                <h:outputText value="#{productDesignDeleteController.selectedBookingClass.name}" >
                                </h:outputText>
                            </p:column>
                        </p:row>
                    </p:panelGrid>
                </p:panel>
                <p:commandButton value="Delete" action="#{navigationController.redirectToViewAllBookingClass()}" actionListener="#{productDesignDeleteController.deleteBookingClass()}" oncomplete="PF('ruleDialog').hide()"/>
            </h:form>
        </p:dialog>

   
    </ui:define>

</ui:composition>